### ISSUE TITLE
include/gdf/utils.h has a static function implementation

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/libgdf#176]
Title says it all: [include/gdf/utils.h](https://github.com/rapidsai/libgdf/blob/master/include/gdf/utils.h) has a static function implementation.

This means that whenever you include it in a translation unit, you have a defined-but-unused function. And since we build with `-Werror`, that means the build will fail.

**Comment by harrism** [comment]
This is a known (but undocumented) issue, that only affects the build with GCC 7+.  I have fixed it in my branch for PR #152. I was unsure why the original author made the function static, so I didn't submit a separate PR for that change alone in case it would affect functionality on GCC < 7.

**Comment by eyalroz** [comment]
>  that only affects the build with GCC 7+.

It affected me with GCC 6.3.0. I was trying to build `blazingdb/master`, and failed because of this, which was surprising; and a quick fix was very obvious, so here we are.
